### ISSUE TITLE
Farneback does not compile with the latest version of setuptools

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-continuousflex#136]
Hi,
Farneback does not compile with the latest version of setuptools. Scipion doesn't freeze this setuptools version as far as I saw. The latest setuptools that we can still use is 64.0.3
There is also a new version of pycuda that installed properly on my ubuntu18, we need to test if this works well on centos7 and freeze to that version.
**It might be a good idea to move towards having our own virtual (conda) environment where these versions (beside all the deep learning version) are installed.**
I will discuss with the scipion team, but if you can be there too when we meet it will be great.
In the meantime, could you (@ilyes-hm , @mms29 ) test if pycuda installs on centos7, Ubuntu20, 16? 
scipion3 pip uninstall pycuda
scipion 3 pip cache purge
scipion3 pip install pycuda==2022.1

Cheers
Mohamad

**Comment by ilyes-hm** [comment]
Hi Mohamad,
Ubuntu 20: I am not able to install pycuda 2022.1, I will try again later today.
Cheers
Ilyes

**Comment by MohamadHarastani** [comment]
Hey man
For some reason pycuda requires nvcc to be in the path. You can install pycuda 2021.1?

**Comment by ilyes-hm** [comment]
Hi,
yes pycuda 2021.1 works fine but I am not able to install 2022.1, I need to update my nvidia drivers, I will try again and let you know.

**Comment by ilyes-hm** [comment]
If your code works fine with pycuda 2021.1 then there is need to update

**Comment by MohamadHarastani** [comment]
I agree. Btw, I am too close to finish with adapting tomoflow to work with the new conda environment. I will attempt to make DeepHEMNMA with with that too and I will put you as a reviewer to test and see if there are adjustments to be made.

**Comment by mms29** [comment]
@MohamadHarastani 
I could install pycuda 2022.1 on my Ubuntu 20

**Comment by MohamadHarastani** [comment]
Thanks @mms29 , we will stick with 2021.1 since it is working everywhere so far
