### ISSUE TITLE
Installation from the plugin manager is not working

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-continuousflex#152]
Hello
I still don't know how to fix this issue, it looks that there is something wrong in the __init__.py, or something is wrong in the plugin manager.
The package installs fine in devel mode properly, but it goes crazy in the plugin manager.
Any help would be appreciated.
Cheers

**Comment by pconesa** [comment]
Hi! I've tested master and I'm getting this error when running installb:

pablo@youyou ~/desarrollo/scipion-em-continuousflex (master)$ scipion3 installb
Scipion v3.0.13 - Eugenius
Error retrieving plugin continuousflex binaries:  'CONDA_PREFIX_1'

The error is in this line:

       lib_path = os.environ['CONDA_PREFIX_1'] + '/envs/continuousflex-' + CF_VERSION + '/lib'

Users very likely will not have (like myself) that variable.

I understand what you are trying to get but maybe it can be done differently?

For example, remember that defineBinaries, is a recipe for a later execution but it should not run anything like:

os.system('ln -f -s ' + lib_path + '/libopenblas* ' + env.getLibFolder())

This should be converted to a command.

**Comment by MohamadHarastani** [comment]
Thanks @pconesa , I will look into that.
As for the CONDA_PREFIX_1, I have just figured out what's the problem.
For you, you can work around the error by activating the base before installing continuousflex.
I will think of a better way, and of isolating the linking of libopenblas in another command.

Cheers

**Comment by pconesa** [comment]
Hi why not, when running whatever you need to run with the conda environment, don't you set LD_LIBRARY_PATH with SCIPION/software/lib folder?

**Comment by MohamadHarastani** [comment]
Hmmm.. actually we do. But we want to add some libraries that are installed on the conda environment too, like arepack, lapack and openblas. I am surprised that conda activate env_name does not add the libraries of env_name to the LD_LIBRARY_PATH!
We are still learning conda, I will play around and be back to test some solutions.

**Comment by pconesa** [comment]
if you installed the through coda they should be available, right?

**Comment by MohamadHarastani** [comment]
That's what I expected, but the libraries are not added to the LD_LIBRARY_PATH when conda is activated
For example
```
harastam@pc4-0002-a:~$ echo $LD_LIBRARY_PATH 
/usr/local/cuda/lib64:/usr/local/IMOD/lib:
harastam@pc4-0002-a:~$ conda activate scipion3
(scipion3) harastam@pc4-0002-a:~$ echo $LD_LIBRARY_PATH 
/usr/local/cuda/lib64:/usr/local/IMOD/lib:

```
Even when this show the activating conda does not make its libraries visible
check this out
```
(scipion3) harastam@pc4-0002-a:~$ ldconfig -v 2>/dev/null | grep -v ^$'\t'
/usr/local/cuda-11.2/targets/x86_64-linux/lib:
/lib/i386-linux-gnu:
/usr/lib/i386-linux-gnu:
/usr/local/lib:
/lib/x86_64-linux-gnu:
/usr/lib/x86_64-linux-gnu:
/lib32:
/usr/lib32:
/libx32:
/usr/libx32:
/lib:
/usr/lib:
```
That's why I was going through $CONDA_PREFIX to navigate to the lib and creating links.

**Comment by pconesa** [comment]
they are not installed as conda libraries..... they are installed "manually" at software/lib

**Comment by MohamadHarastani** [comment]
Now I understand what you mean. We are using these of course. But we need arepack, lapack and openblas, which are not installed in scipion/software/lib. So we install them on our continuousflex-git conda environment and we link them to scipion/software/lib. If you know a better way, I am all ears.

**Comment by pconesa** [comment]
I don't see (in master) the code to install arepack, lapack and openblas 
in the continuousflex env.

**Comment by MohamadHarastani** [comment]
It's in the yaml file
https://github.com/scipion-em/scipion-em-continuousflex/blob/master/continuousflex/__init__.py#L121

**Comment by MohamadHarastani** [comment]
Hi @pconesa 
Can you show me the error that you get with CONDA_PREFIX? I installed everything from scratch and couldn't reproduce the error. Is it that you base environment and the remaining environments are different places? can you show me what you get when you type "conda env list"?
I removed the linking, it was there by mistake. You can test the new master branch.
I am getting a very confusing thing when installing from the plugin manager. I can install with "skip binaries" and install the binaries one by one, but I cannot install them all together. The first binary is the conda environment, and the remaining binaries require this binary to be installed first. They don't go in order when installed from the plugin manager.

**Comment by pconesa** [comment]
Hi, you are assuming everyone has conda initialized, and this is not my case. In a new terminal, I do not have conda available and therefore I do not have any conda base env.

Regarding the plugin manager, I see, your's is the first case we have binaries sharing the same environment...Is it too much to make it just one big installation?

**Comment by MohamadHarastani** [comment]
Thanks Pablo for the feedback. It is true that conda for me is always initialized. I will try to reproduce the case where conda is not initialized. We can't make them one big installation, each binary has its own problems.
I will give it another look this week.

**Comment by pconesa** [comment]
So, you want 3 different environments?

**Comment by MohamadHarastani** [comment]
It might be too slow to create all of these environments, we actually have 4 binaries (NMA, Genesis, DeepLearning, OpticalFlow).

**NMA:**
It requires arpack and lapack libraries to compile. It is very essential, almost every method requires it. It doesn't require Cuda, we have some CPU clusters that we can use with HEMNMA, so we need it to be separated from the other binaries. All other binaries are kind of optional.
**Genesis:**
It requires arpack, lapack and openblas. It is a little tricky to install so we don't want to merge it with NMA. Again, it doesn't require Cuda to install and we might use it on CPU clusters.
**DeepLearning:**
Requires pytorch, tensorflow, etc.  Heavy to install and requires Cuda, so cannot be merged with anything else.
**OpticalFlow:**
Requires PyCuda which is not stable. Requires Cuda in the path (nvcc). So better kept separate from anything else.

Feel free to propose any solution @pconesa @mms29

**Comment by pconesa** [comment]
Then I'd create  one conda enviroment per "binary" not sharing a base one "Continuousflex"  (is this what you were trying?)

If NMA does not require a environment then is fine as it is.

then create one for Genesis, Depplearning and OpticalFlow ..... please do not forget to prefix their name, Deeplearnning and OpticalFlow are quite generic. SOmething like
cf-depplearning-0.5 (in case you want to introduce a version in the environment name.

**Comment by MohamadHarastani** [comment]
Okay this will require some refactoring. I will start with that now.
Thanks @pconesa  for the continuous support!

**Comment by mms29** [comment]
Hi there, 
@pconesa, @MohamadHarastani do you think we should consider completely removing the installation of standard libraries like lapack/blas/arpack and make them as requirements for the user? I believe most of them are already installed on most machines considering the number of programs using them. @pconesa is it something that others do ?
It will greatly simplify the installation process (no more python environment  for NMA and GENESIS which are just fortran binaries) Leaving just Deeplearning and opticalFlow.

**Comment by MohamadHarastani** [comment]
Hi Remi
This will complicate the installation on clusters when the user does not have sudo rights. I have access to clusters that are very poorly configured and I don't have sudo rights. Even worse, no one wants to change a thing since the old programs they are using are working magically on these clusters.
I have just figured out how to do it, it will be solved tomorrow.
Cheers

**Comment by mms29** [comment]
That's a good point, but isn't blas and lapack already installed on your cluster ? I wonder how they could build most programs

**Comment by MohamadHarastani** [comment]
> That's a good point, but isn't blas and lapack already installed on your cluster ? I wonder how they could build most programs
I have just navigated through all the directories I got for `ldconfig -v 2>/dev/null | grep -v ^$'\t'` on 2 out of 4 clusters, and none of them had arepack.
Anyway, I think I solved the problem to a certain extent.

**Comment by MohamadHarastani** [comment]
@pconesa if you can give the installation a try (in master or plugin manager) I will appreciate it

**Comment by pconesa** [comment]
Hi among all software installed by scipion, only continuous flex needs 
arpack, lapack and openblas.

Not sure if other use them, if so, they found a way to ship them with 
their code.

  Conda environments are de default way to go.  to isolate libraries and 
separate environments.

**Comment by MohamadHarastani** [comment]
Thanks @pconesa. We recently moved to using conda for installing arepack and lapack. 
Now I am installing the conda environment in Scipion/software/em which gives two advantages:
1- I know where is the location of my conda environment to borrow libraries. 
2- when the plugin uninstalls, it deletes the conda environment with it.
Maybe this should be adapted to other plugins and even to Scipion.
We fixed the installation issues, so I will be happy if you test installing continuousflex and give me feedback.

**Comment by pconesa** [comment]
Hi, I've installed using installb all the environments except the one with hyphens. It seem the name can't have hyphens.

I'd like to insist in having a more specific environment names: Deeplearning or OpticalFlow are too generic.

**Comment by MohamadHarastani** [comment]
Hi Pablo
Are you sure you pulled the changes? I removed Deeplearning or OpticalFlow as binaries and kept them under the umbrella of one library called ContinuousFlex, which conditions their installation to the case where you have Cuda nvcc in your path. It might be that you are still seeing the old names in software/em since they were not deleted, but they should not be there anymore.
The one with the hyphens is MD-NMMD-Genesis. I will ask Remi to come up with another name.
