### ISSUE TITLE
issue for installation

### ISSUE THREAD

**Issue by zorowangtt** [scipion-em/scipion-em-continuousflex#194]
Collecting pyparsing<3.1,>=2.3.1 (from matplotlib->-r /home/tingting/opt/scipion-em-continuousflex/continuousflex/condaenv.qmah64gz.requirements.txt (line 4))
  Using cached pyparsing-3.0.9-py3-none-any.whl.metadata (4.2 kB)

The conflict is caused by:
    The user requested matplotlib
    scipion-pyworkflow 3.8.0 depends on matplotlib==3.7.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/scipion-em/scipion-pyworkflow.git /tmp/pip-req-build-q_puns85
  Running command git checkout -b master --track origin/master
  Switched to a new branch 'master'
  branch 'master' set up to track 'origin/master'.
ERROR: Cannot install -r /home/tingting/opt/scipion-em-continuousflex/continuousflex/condaenv.qmah64gz.requirements.txt (line 12) and matplotlib because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

failed

CondaEnvException: Pip failed

ERROR: File or folder '/home/tingting/opt/scipion/software/em/ContinuousFlex-3.4.1/last-pull-3.4.1.txt' not found after running 'eval "$(/home/tingting/opt/miniconda3/bin/conda shell.bash hook)"&&conda env create -f /home/tingting/opt/scipion-em-continuousflex/continuousflex/conda_noCuda.yaml --prefix . --yes&& conda env update --prefix . --file=/home/tingting/opt/scipion-em-continuousflex/continuousflex/conda.yaml && touch last-pull-3.4.1.txt'.
(base) [tingting@corfu scipion-em-continuousflex]$ conda activate scipion

**Comment by menmt0930** [comment]
I got the same error when installing.
