### ISSUE TITLE
Adding trajectory animations to PDB dimred protocol

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-continuousflex#95]
Our current PDB dimred protocol has a viewer that only shows the low dimensional space, but does not allow using it to generate animations. It will be an enhancement (from Labels), and Remi can be assigned (from Assignees).
When a PR is created, it should be linked to this issue. So when the PR is closed, it will close this issue automatically.

Cheers

**Comment by mms29** [comment]
Done
